//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sellYourCar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }
        public System.DateTime yearOfProduction { get; set; }
        public int mileage { get; set; }
        public short capacity { get; set; }
        public short horsePower { get; set; }
        public byte numberOfDoors { get; set; }
        public byte numberOfSeats { get; set; }
        public decimal price { get; set; }
        public int brandID { get; set; }
        public int typeID { get; set; }
        public int fuelTypeID { get; set; }
        public int colorID { get; set; }
        public int countryID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual CarType CarType { get; set; }
        public virtual Color Color { get; set; }
        public virtual Country Country { get; set; }
        public virtual Fuel Fuel { get; set; }
    }
}
